### PR TITLE
SPIKE: Select fields for contentful items

### PR DESCRIPTION
**Pull request by ianhowe76**
Implements contentful selection only of requested fields
Uses caching logic for query to ensure that minimum number of calls to contentful are performed

TODO: 
* [ ] Wiki page to describe implementation and test queries
* [ ] Fix unit tests
* [ ] Discard this and revert other changes via #8

### CODE REVIEW

**Comment by yarnball** [comment]
Nice.

A few couple thoughts:

- If we're specifying each field- this request could become very verbose (packet size)
- IIRC, we can only make one request per content type

**Comment by rnsloan** [comment]
> Discard this and revert other changes via #8
?

**Comment by Soliah** [comment]
I'm thinking this is super complicated. Do the tests pass? Do we test the new functionality?

**Comment by ianhowe76** [comment]
@Soliah will discuss findings at brown meeting today (https://wiki.scentregroup.com/display/PM/Spike%3A+Updating+cf-graphql+to+get+only+selected+fields)
Don't think this will get merged but a few lessons learnt

**Pull request closed without merging**
